# Start-Up Funding Analysis

In [1]:
import pandas as pd
import numpy as np

In [2]:
df = pd.read_csv('./Datasets/startup_funding.csv')
df.head()

,Sr No,Date dd/mm/yyyy,Startup Name,Industry Vertical,SubVertical,City Location,Investors Name,InvestmentnType,Amount in USD,Remarks
0,1,09/01/2020,BYJU’S,E-Tech,E-learning,Bengaluru,Tiger Global Management,Private Equity Round,"20,00,00,000",NaN
1,2,13/01/2020,Shuttl,Transportation,App based shuttle service,Gurgaon,Susquehanna Growth Equity,Series C,"80,48,394",NaN
2,3,09/01/2020,Mamaearth,E-commerce,Retailer of baby and toddler products,Bengaluru,Sequoia Capital India,Series B,"1,83,58,860",NaN
3,4,02/01/2020,https://www.wealthbucket.in/,FinTech,Online Investment,New Delhi,Vinod Khatumal,Pre-series A,"30,00,000",NaN
4,5,02/01/2020,Fashor,Fashion and Apparel,Embroiled Clothes For Women,Mumbai,Sprout Venture Partners,Seed Round,"18,00,000",NaN

In [6]:
df.tail()

,Sr No,Date dd/mm/yyyy,Startup Name,Industry Vertical,SubVertical,City Location,Investors Name,InvestmentnType,Amount in USD,Remarks
3039,3040,29/01/2015,Printvenue,NaN,NaN,NaN,Asia Pacific Internet Group,Private Equity,"45,00,000",NaN
3040,3041,29/01/2015,Graphene,NaN,NaN,NaN,KARSEMVEN Fund,Private Equity,"8,25,000",Govt backed VC Fund
3041,3042,30/01/2015,Mad Street Den,NaN,NaN,NaN,"Exfinity Fund, GrowX Ventures.",Private Equity,"15,00,000",NaN
3042,3043,30/01/2015,Simplotel,NaN,NaN,NaN,MakeMyTrip,Private Equity,NaN,"Strategic Funding, Minority stake"
3043,3044,31/01/2015,couponmachine.in,NaN,NaN,NaN,UK based Group of Angel Investors,Seed Funding,"1,40,000",NaN

In [7]:
df.sample(10)

,Sr No,Date dd/mm/yyyy,Startup Name,Industry Vertical,SubVertical,City Location,Investors Name,InvestmentnType,Amount in USD,Remarks
2360,2361,26/10/2015,Flexing It,Professionals & Project Search Marketplace,NaN,New Delhi,undisclosed private investors,Seed Funding,"5,00,000",NaN
1666,1667,03/05/2016,iDreamCareer,Consumer Internet,Career Planning Services Portal,New Delhi,Brand Capital,Private Equity,NaN,NaN
657,658,17/08/2017,Get Simpl,Consumer Internet,Payment Solution Mobile app,Mumbai,"Green Visor Capital LP II, IA Venture Strategi...",Seed Funding,NaN,NaN
267,268,22/05/2018,Vola,Finance,Micro Lending Platform,Bengaluru,Credika and unnamed angel investors,Seed/ Angel Funding,"5,00,000",NaN
700,701,18/07/2017,Ambee,Consumer Internet,Ambulance Aggregation Services,Hyderabad,"Uber Technologies Inc, Amaya Capital LLP",Seed Funding,NaN,NaN
10,11,13/12/2019,Rivigo,Technology,Logistics Services and Solutions,Gurgaon,"SAIF Partners, Spring Canter Investment Ltd.",Series F,"2,00,00,000",NaN
882,883,12/04/2017,Emiza,Logistics,Third Party Logistics provider,Mumbai,"Mayfield, Nishant Rao, Dileep Nath",Private Equity,"45,00,000",NaN
2117,2118,03/12/2015,Anakage,Product Learning platform,NaN,Bangalore,CIO Angel Network (CAN),Seed Funding,NaN,NaN
2386,2387,02/09/2015,HolaChef,Food Delivery Platform,NaN,Mumbai,Ratan Tata,Private Equity,NaN,Part of Series A raised in June 2015
677,678,01/07/2017,Billion Loans,Consumer Internet,Peer to Peer Lending platform,Bangalore,Reliance Corporate Advisory Services Ltd,Seed Funding,"10,00,000",NaN

In [3]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 3044 entries, 0 to 3043
Data columns (total 10 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Sr No              3044 non-null   int64
 1   Date dd/mm/yyyy    3044 non-null   str
 2   Startup Name       3044 non-null   str
 3   Industry Vertical  2873 non-null   str
 4   SubVertical        2108 non-null   str
 5   City  Location     2864 non-null   str
 6   Investors Name     3020 non-null   str
 7   InvestmentnType    3040 non-null   str
 8   Amount in USD      2084 non-null   str
 9   Remarks            419 non-null    str
dtypes: int64(1), str(9)
memory usage: 237.9 KB

In [5]:
df['Remarks'].value_counts()

Remarks
Series A                             175
Series B                              63
Pre-Series A                          37
Series C                              28
Strategic Investment                  11
                                    ...
More Details                           1
To fund edu startups                   1
Majority Stake                         1
Govt backed VC Fund                    1
Strategic Funding, Minority stake      1
Name: count, Length: 72, dtype: int64

In [9]:
# drop remarks column
df.drop(columns=['Remarks'], inplace=True)

In [12]:
# set sr no to default index
df.set_index('Sr No', inplace=True)

In [13]:
df.columns

Index(['Date dd/mm/yyyy', 'Startup Name', 'Industry Vertical', 'SubVertical',
       'City  Location', 'Investors Name', 'InvestmentnType', 'Amount in USD'],
      dtype='str')

In [15]:
# changing columns name
df.columns=['date', 'startup', 'vertical', 'subvertical', 'city', 'inverstors', 'inv_types', 'amount']

In [17]:
df.columns

Index(['date', 'startup', 'vertical', 'subvertical', 'city', 'inverstors',
       'inv_types', 'amount'],
      dtype='str')

In [18]:
df.head()

,date,startup,vertical,subvertical,city,inverstors,inv_types,amount
Sr No,,,,,,,,
1,09/01/2020,BYJU’S,E-Tech,E-learning,Bengaluru,Tiger Global Management,Private Equity Round,"20,00,00,000"
2,13/01/2020,Shuttl,Transportation,App based shuttle service,Gurgaon,Susquehanna Growth Equity,Series C,"80,48,394"
3,09/01/2020,Mamaearth,E-commerce,Retailer of baby and toddler products,Bengaluru,Sequoia Capital India,Series B,"1,83,58,860"
4,02/01/2020,https://www.wealthbucket.in/,FinTech,Online Investment,New Delhi,Vinod Khatumal,Pre-series A,"30,00,000"
5,02/01/2020,Fashor,Fashion and Apparel,Embroiled Clothes For Women,Mumbai,Sprout Venture Partners,Seed Round,"18,00,000"

In [21]:
df['amount'].isnull().value_counts()

amount
False    2084
True      960
Name: count, dtype: int64

In [22]:
df[df['amount'].isnull()]

,date,startup,vertical,subvertical,city,inverstors,inv_types,amount
Sr No,,,,,,,,
145,01/10/2018,Northmist,Fashion,Mens Wear,Delhi,Prashant Jaiswal,Seed/ Angel Funding,NaN
156,04/09/2018,HappyGoEasy,Consumer Internet,Online Travel Agecy,Gurugram,"Korea Investment Partners (KIP), Samsung and C...",Private Equity,NaN
158,05/09/2018,Mad Street Den,Technology,Computer Vision And Artificial Intelligence (A...,Chennai,KDDI\\xc2\\xa0,Private Equity,NaN
166,01/08/2018,HealthFin,Finance,Patient Financing Platform,Pune,"Axilor, Sprout Venture Partners and others",Seed/ Angel Funding,NaN
190,01/07/2018,Leena AI,Technology,HR Virtual Agent For Employees,Gurugram,Y Combinator,Seed/ Angel Funding,NaN
...,...,...,...,...,...,...,...,...
3028,21/05/2015,Knit,NaN,NaN,NaN,"Rohit Jain, Amit Rambhia & Others",Seed Funding,NaN
3031,22/01/2015,Freshmonk,NaN,NaN,NaN,"August Capital Partners, Michael Blakey",Seed Funding,NaN
3032,22/01/2015,Englishleap.com,NaN,NaN,NaN,ANALEC,Private Equity,NaN
3036,24/01/2015,Impartus,NaN,NaN,NaN,Kaizen Private Equity,Private Equity,NaN
3043,30/01/2015,Simplotel,NaN,NaN,NaN,MakeMyTrip,Private Equity,NaN

In [36]:
# replacing nan to zero in amount column
df['amount'] = df['amount'].replace(np.nan, '0')

In [38]:
df['amount'].isnull().sum()

np.int64(0)

In [75]:
# changing dtype of amount col
df['amount'] = df['amount'].str.replace(',','')
df['amount'] = df['amount'].str.replace('undisclosed','0')
df['amount'] = df['amount'].str.replace('0u0n0k0n0o0w0n0','0')
df['amount'] = df['amount'].str.replace('0U0n0d0i0s0c0l0o0s0e0d0','0')

df = df[df['amount'].str.isdigit()]
df['amount'] = df['amount'].astype(np.float64)

In [76]:
df.info()

<class 'pandas.DataFrame'>
Index: 3029 entries, 1 to 3044
Data columns (total 8 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   date         3029 non-null   str
 1   startup      3029 non-null   str
 2   vertical     2858 non-null   str
 3   subvertical  2104 non-null   str
 4   city         2849 non-null   str
 5   inverstors   3005 non-null   str
 6   inv_types    3027 non-null   str
 7   amount       3029 non-null   float64
dtypes: float64(1), str(7)
memory usage: 213.0 KB

In [80]:
# converting usd to inr(cr)
def convert_to_inr(usd):
    return (usd*95.2) / 10000000
df['amount'] = df['amount'].apply(convert_to_inr)

In [90]:
# converting date from str to datetime
pd.to_datetime(df['date'], format='%d/%m/%y', errors='coerce')

Sr No
1      NaT
2      NaT
3      NaT
4      NaT
5      NaT
        ..
3040   NaT
3041   NaT
3042   NaT
3043   NaT
3044   NaT
Name: date, Length: 3029, dtype: datetime64[s]

In [89]:
df['date']

Sr No
1       09/01/2020
2       13/01/2020
3       09/01/2020
4       02/01/2020
5       02/01/2020
           ...
3040    29/01/2015
3041    29/01/2015
3042    30/01/2015
3043    30/01/2015
3044    31/01/2015
Name: date, Length: 3029, dtype: str